# Generated by Django 3.0.8 on 2020-09-02 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0006_auto_20200902_1626'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name_plural': 'Faculty'},
        ),
        migrations.AlterModelTable(
            name='faculty',
            table='College',
        ),
    ]
