# Generated by Django 3.0.8 on 2020-09-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=30)),
                ('Last_Name', models.CharField(max_length=30)),
                ('Branch', models.CharField(max_length=10)),
                ('Age', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
