# Generated by Django 3.0.8 on 2020-09-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_auto_20200902_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='Qualification',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
