# Generated by Django 3.0.8 on 2020-09-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='Book_Image',
            field=models.ImageField(null=True, upload_to='bookimage/'),
        ),
    ]
