# Generated by Django 3.0.8 on 2020-09-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0005_auto_20200902_1334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={},
        ),
        migrations.AlterField(
            model_name='faculty',
            name='Email',
            field=models.EmailField(default='example@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='Name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='Phone',
            field=models.CharField(help_text='Enter 10 Digit Mobile Number', max_length=10),
        ),
        migrations.AlterModelTable(
            name='faculty',
            table=None,
        ),
    ]
